{
 "title": "ML Service Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ModelType",
    "query": {
     "query": "label_values(flask_http_request_duration_seconds_count, model_type)"
    }
   },
   {
    "name": "Gender",
    "query": {
     "query": "label_values(flask_http_request_duration_seconds_count, gender)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current RPM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) * 60",
     "legendFormat": "Текущий RPM"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_count{status=~\"5..\", model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) or vector(0)) / sum(rate(flask_http_request_duration_seconds_count{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) * 100",
     "legendFormat": "Доля ошибок"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m]))",
     "legendFormat": "Общий RPS"
    }
   ]
  },
  {
   "title": "RPS by Model Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) by (model_type)",
     "legendFormat": "Модель: {{model_type}}"
    }
   ]
  },
  {
   "title": "HTTP Errors Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=~\"[45]..\", model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) by (status)",
     "legendFormat": "Статус {{status}}"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Handle Latency P90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(flask_http_request_duration_seconds_bucket{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) by (le)) * 1000",
     "legendFormat": "Latency P90 (Ручка)"
    }
   ]
  },
  {
   "title": "Model Inference Time P90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(model_inference_seconds_bucket{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) by (le)) * 1000",
     "legendFormat": "Inference Time P90 (Берт)"
    }
   ]
  },
  {
   "title": "Average Response Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m]))) * 1000",
     "legendFormat": "Среднее время обработки"
    }
   ]
  },
  { "title": "Probas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Distribution of Predictions (Probas)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(model_inference_seconds_sum{model_type=~\"$ModelType\", gender=~\"$Gender\"}[1m])) by (gender, model_type)",
     "legendFormat": "Распределение: {{gender}} ({{model_type}})"
    }
   ]
  }
 ]
}